#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfe0d;
constexpr uint24_t FX_DATA_BYTES = 123523;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x0092DC;
  constexpr uint24_t SFX_Victory = 0x009380;
  constexpr uint24_t SFX_XPGain = 0x009434;
  constexpr uint24_t SFX_Three_Inc = 0x009448;
  constexpr uint24_t SFX_Three_Dec = 0x009464;
  constexpr uint24_t SFX_PlayerBlip = 0x009480;
  constexpr uint24_t SFX_EnemyBlip = 0x009490;
  constexpr uint24_t SFX_Explosion = 0x0094A0;
  constexpr uint24_t SFX_DoubleBeep = 0x0094E4;
  constexpr uint24_t SFX_DoubleBeepDown = 0x0094F4;
  constexpr uint24_t SFX_Bet1 = 0x009504;
  constexpr uint24_t SFX_Bet2 = 0x00950C;
  constexpr uint24_t SFX_Bet3 = 0x009514;
  constexpr uint24_t SFX_Bet4 = 0x00951C;
  constexpr uint24_t SFX_Bet5 = 0x009524;
  constexpr uint24_t SFX_Bet6 = 0x00952C;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x009534;
  constexpr uint24_t Sound_Volume = 0x00C536;
  constexpr uint24_t Sound_Checkbox = 0x00CD78;
  constexpr uint24_t Title = 0x00CD86;
  constexpr uint24_t Title_Background = 0x0121E8;
  constexpr uint24_t GameOver = 0x012DEA;
  constexpr uint24_t Pause = 0x01314C;
  constexpr uint24_t Cards = 0x01374E;
  constexpr uint24_t Cards_Back = 0x01D0E0;
  constexpr uint24_t Cards_Highlight = 0x01D6CA;
  constexpr uint24_t HUD = 0x01DCB4;
  constexpr uint24_t ArrowUpDown = 0x01DE36;
  constexpr uint24_t Frame_LH = 0x01DE47;
  constexpr uint24_t Frame_RH = 0x01E065;
}

