#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfdc4;
constexpr uint24_t FX_DATA_BYTES = 142152;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x00DBA1;
  constexpr uint24_t SFX_Victory = 0x00DC45;
  constexpr uint24_t SFX_XPGain = 0x00DCF9;
  constexpr uint24_t SFX_Three_Inc = 0x00DD0D;
  constexpr uint24_t SFX_Three_Dec = 0x00DD29;
  constexpr uint24_t SFX_PlayerBlip = 0x00DD45;
  constexpr uint24_t SFX_EnemyBlip = 0x00DD55;
  constexpr uint24_t SFX_Explosion = 0x00DD65;
  constexpr uint24_t SFX_DoubleBeep = 0x00DDA9;
  constexpr uint24_t SFX_DoubleBeepDown = 0x00DDB9;
  constexpr uint24_t SFX_Bet1 = 0x00DDC9;
  constexpr uint24_t SFX_Bet2 = 0x00DDD1;
  constexpr uint24_t SFX_Bet3 = 0x00DDD9;
  constexpr uint24_t SFX_Bet4 = 0x00DDE1;
  constexpr uint24_t SFX_Bet5 = 0x00DDE9;
  constexpr uint24_t SFX_Bet6 = 0x00DDF1;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x00DDF9;
  constexpr uint24_t Sound_Volume = 0x010DFB;
  constexpr uint24_t Sound_Checkbox = 0x01163D;
  constexpr uint24_t Title = 0x01164B;
  constexpr uint24_t Title_Background = 0x016AAD;
  constexpr uint24_t GameOver = 0x0176AF;
  constexpr uint24_t Pause = 0x017A11;
  constexpr uint24_t Cards = 0x018013;
  constexpr uint24_t Cards_Back = 0x0219A5;
  constexpr uint24_t Cards_Highlight = 0x021F8F;
  constexpr uint24_t HUD = 0x022579;
  constexpr uint24_t ArrowUpDown = 0x0226FB;
  constexpr uint24_t Frame_LH = 0x02270C;
  constexpr uint24_t Frame_RH = 0x02292A;
}

